theme: jekyll-theme-time-machine
title: DJ Tankdilla
email: djtankdilla@gmail.com
description: My latest stories and photos
url: https://djtankdilla.github.io/djtankdilla
twitter_username: djtankdilla
github_username: djtankdilla
