theme: jekyll-theme-time-machine
title: DJ Tankdilla
email: djtankdilla@gmail.com
description: bringing the kingdom outside of the four walls
url: https://djtankdilla.github.io/djtankdilla
twitter_username: djtankdilla
github_username: djtankdilla
